### PR TITLE
Add support for Flannel using rke_network_t

### PR DESCRIPTION
**Pull request by superseb**
https://github.com/rancher/rke/issues/2620

Used as:

```
         securityContext:
           seLinuxOptions:
             type: rke_network_t
```

### CODE REVIEW

**Review by cmurphy — APPROVED** [review]

**Review by nickgerace — APPROVED** [review]
Reviewed for syntax only

**Comment by dweomer** [comment]
I can see why the custom type but is this actually specific to flannel or should it maybe be something like rke_network_t?

**Comment by superseb** [comment]
Only Flannel needs this at the moment, if any other plugins need a type at some point, I guess the choice here is to create a generic one (rke_network_t) now and add all requirements that come from others to this type or create types per plugin. All requirements into one generic type is easier but is not least privilege (at least, we don't know but some plugins might need more than others for example), while having a type per plugin could be considered overhead or too similar.

**Comment by superseb** [comment]
@dweomer Any problems with this or do you think it will end it up in generic type anyway so better start now? Based on issues in Calico and Weave, its not happening soon (dropping privileged)

**Comment by dweomer** [comment]
> @dweomer Any problems with this or do you think it will end it up in generic type anyway so better start now? Based on issues in Calico and Weave, its not happening soon (dropping privileged)

When I initially reviewed this it was on my phone because of reasons. I thought/assumed that there would be file transitions/contexts associated with the type but that doesn't seem to be the case. I guess my lingering concern is that this should really be a generic, albeit privileged, network-oriented service type as opposed to named after the network service that first encountered the problem. If the network service is only ever going to be flannel than it is fine.

**Review by dweomer — APPROVED** [review]
LGTM but with a naming concern/caveat mentioned here: https://github.com/rancher/rancher-selinux/pull/8#issuecomment-890012458

**Comment by superseb** [comment]
@dweomer We can't guarantee that, if Calico/Weave start dropping privileged and we need to fix it, its going to happen the same way. So that potentially could be `rke_calico_t` and `rke_weave_t`. So based on your comment, you advise to use `rke_network_t` which I think I am fine with.

**Review by dweomer — APPROVED** [review]

**Comment by superseb** [comment]
@dweomer @cmurphy if any of you have bandwidth to merge and create a new RPM, that would be appreciated.

**Review by cmurphy — APPROVED** [review]

**Pull request merged**
